spring:
  config:
    activate:
      on-profile: "auth"

oauth2:
  user:
    github:
      client-id: 3be09fccc24e823c9e9a
      client-secret: ce0923c8379ef2528008ae5c5755edb55f4094aa
      redirect-uri: http://localhost:8080/login/github/callback
    google:
      client-id: 564035895083-n2r1rlt9t4sokm7ma0rpsaj8bvc06e02.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/login/google/callback
    naver:
      client-id: BVdMjTl8jZEwvXxrkOt3
      client-secret: kFQXK9mpoJ
      redirect-uri: http://localhost:8080/login/naver/callback
    kakao:
      client-id: e9fa708fb8f556fd1704d54f1c867f14
      client-secret: p1KcWa03iCOPgccKysYyXQzMA96EfQpZ
      redirect-uri: http://localhost:8080/login/kakao/callback

  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
jwt:
  token:
    secret-key: secretzinoking
  access-token:
    expire-length: 600000
  refresh-token:
    expire-length: 1800000
