spring:
  config:
    activate:
      on-profile: "auth"

oauth2:
  user:
    github:
      client-id: ${{ env.GH_CLIENT_ID }}
      client-secret: ${{ env.GH_CLIENT_SECRET }}
      redirect-uri: ${{ env.GH_REDIRECT_URI }}
    google:
      client-id: ${{ env.GOOGLE_CLIENT_ID }}
      client-secret: ${{ env.GOOGLE_CLIENT_SECRET }}
      redirect-uri: ${{ env.GOOGLE_REDIRECT_URI }}
    naver:
      client-id: ${{ env.NAVER_CLIENT_ID }}
      client-secret: ${{ env.NAVER_CLIENT_SECRET }}
      redirect-uri: ${{ env.NAVER_REDIRECT_URI }}
    kakao:
      client-id: ${{ env.KAKAO_CLIENT_ID }}
      client-secret: ${{ env.KAKAO_CLIENT_SECRET }}
      redirect-uri: ${{ env.KAKAO_REDIRECT_URI }}

  provider:
    github:
      token-uri: ${{ env.GH_TOKEN_URI }}
      user-info-uri: ${{ env.GH_USER_INFO_URI }}
    google:
      token-uri: ${{ env.GOOGLE_TOKEN_URI }}
      user-info-uri: ${{ env.GOOGLE_USER_INFO_URI }}
    naver:
      token-uri: ${{ env.NAVER_TOKEN_URI }}
      user-info-uri: ${{ env.NAVER_USER_INFO_URI }}
    kakao:
      token-uri: ${{ env.KAKAO_TOKEN_URI }}
      user-info-uri: ${{ env.KAKAO_USER_INFO_URI }}

jwt:
  token:
    secret-key: ${{ env.JWT_SECRET_KEY }}
  access-token:
    expire-length: 600000
  refresh-token:
    expire-length: 1800000

env:
  GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  GH_REDIRECT_URI: ${{ secrets.GH_REDIRECT_URI }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
  NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
  NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
  NAVER_REDIRECT_URI: ${{ secrets.NAVER_REDIRECT_URI }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
  KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
  GH_TOKEN_URI: ${{ secrets.GH_TOKEN_URI }}
  GH_USER_INFO_URI: ${{ secrets.GH_USER_INFO_URI }}
  GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
  GOOGLE_USER_INFO_URI: ${{ secrets.GOOGLE_USER_INFO_URI }}
  NAVER_TOKEN_URI: ${{ secrets.NAVER_TOKEN_URI }}
  NAVER_USER_INFO_URI: ${{ secrets.NAVER_USER_INFO_URI }}
  KAKAO_TOKEN_URI: ${{ secrets.KAKAO_TOKEN_URI }}
  KAKAO_USER_INFO_URI: ${{ secrets.KAKAO_USER_INFO_URI }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
