spring:
  profiles:
    active:
      - dev

    group:
      local: "db-local"
      dev: "db-dev"
      test: "db-test"
    include:
      - db
      - auth

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
