spring:
  config:
    activate:
      on-profile: "auth"

oauth2:
  user:
    github:
      client-id: ${GH_CLIENT_ID}
      client-secret: ${GH_CLIENT_SECRET}
      redirect-uri: ${GH_REDIRECT_URI}
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: ${NAVER_REDIRECT_URI}
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}

  provider:
    github:
      token-uri: ${GH_TOKEN_URI}
      user-info-uri: ${GH_USER_INFO_URI}
    google:
      token-uri: ${GOOGLE_TOKEN_URI}
      user-info-uri: ${GOOGLE_USER_INFO_URI}
    naver:
      token-uri: ${NAVER_TOKEN_URI}
      user-info-uri: ${NAVER_USER_INFO_URI}
    kakao:
      token-uri: ${KAKAO_TOKEN_URI}
      user-info-uri: ${KAKAO_USER_INFO_URI}

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
  access-token:
    expire-length: 600000
  refresh-token:
    expire-length: 1800000
