global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'spring-app'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'spring-app:8080' ]


#scrape_configs:
#  - job_name: 'spring_app'
#    ec2_sd_configs:
#      - region: '<aws_region>'
#        access_key: '<aws_access_key>'
#        secret_key: '<aws_secret_key>'
#        port: 8080
#    relabel_configs:
#      - source_labels: [__meta_ec2_tag_Name]
#        regex: '<your_auto_scaling_group_name>'
#        action: keep
#      - source_labels: [__address__]
#        target_label: __address__
#        replacement: '${1}:<your_application_port>'
#      - source_labels: [__meta_ec2_instance_id]
#        target_label: instance
