name: BE - CI(Init repo -> CI Gradle Cache -> Test)

on:
  pull_request:
    branches: [main]
    paths:
      [
        "src/**",
        "build.gradle",
      ]
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  be-test:
    name: Test SpringBoot
    runs-on: ubuntu-20.04

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
          cache: gradle

      - name: Use gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test And Analyze
        run: ./gradlew test

      - name: Notify Slack on Success
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          title: ${{ github.repository }}
          author_name: Github Action Test
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          color: good
          github_token: ${{ secrets.GH_TOKEN }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          title: ${{ github.repository }}
          author_name: Github Action Test
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          color: fail
          github_token: ${{ secrets.GH_TOKEN }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
